build:
  image: maven:3-eclipse-temurin-21
  script:
    - mvn package

  services:
    - name: postgres:18.4
      alias: postgres

    - name: docker:dind
      alias: docker

  variables:
    POSTGRES_DB: school_db
    POSTGRES_USER: school_user
    POSTGRES_PASSWORD: school_password

    DB_USERNAME: school_user
    DB_PASSWORD: school_password
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/school_db

    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2





