services:
  db:
    image: postgres:18.4
    container_name: school-app-postgres

    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: