spring:
  application:
    name: school-management-app

  config:
    import: "optional:file:./.env[.properties]"

  datasource:
    url: jdbc:postgresql://localhost:5432/school_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    locations: "classpath:db/migration"

school:
  console:
    enabled: true
  data-generator:
    students-count: 200
    groups-count: 10
    courses-count: 10
  group-assignment:
    min-students: 0
    max-students: 30
  student-courses-assignment:
    min-courses: 1
    max-courses: 3

logging:
  level:
    root: info
    com.foxminded.schoolmanagementapp: debug



  

